name: Development Partner Request
description: This is the template to request a RISC-V Development Partner work.
title: "Brief description please"
assignees: jjscheel
labels: "Agenda Item"
body:
  - type: markdown
    attributes:
      value: |
        Please enter as much information as you can about the request.  Do not worry if you cannot complete everything.
  - type: dropdown
    id: tech-group
    attributes:
      label: Technical Group
      description: Which technical groups is requesting the work?
      options:
        - Applications & Tools HC
        - Architecture Test SIG
        - Code Size Reduction TG
        - Crypto TG
        - Debug TG
        - Golden Model SIG
        - ISA Infrastructure HC
        - Pointer Masking TG
        - Privileged Softwrae HC
        - Privileged Spec IC
        - Profiles TG
        - Security HC
        - SOC Infrastructure HC
        - Technology HC
        - Unprivileged Spec IC
        - Other
    validations:
      required: true
  - type: input
    id: taskname
    attributes:
      label: ratification-pkg
      description: Name of the ratification package used for the work.  (This name should be common for all requests of a given package.)
      placeholder: ex. Code Size, Debug, Priv 1.12, Profiles, Scalar Krypto
    validations:
      required: true
  - type: input
    id: tech-liason
    attributes:
      label: Technical Liaison
      description: 'Name (email) for technical liaison.  Note: this person will be assigned to the issue along with the developer.'
      placeholder: ex. Jane Doe
    validations:
      required: true
  - type: dropdown
    id: task-category
    attributes:
      label: Task Category
      description: What is the required skillset?
      options:
        - Arch Tests
        - Compilers/Toolchain
        - Libraries
        - Runtimes
        - SAIL model
        - Simulators
        - Specification
        - OS
        - Proof of Concept
        - Other
    validations:
      required: true
  - type: checkboxes
    id: task-subcategory
    attributes:
      label: Task Sub Category
      description: Select specific subcategories as needed.
      options:
        - label: gcc
        - label: binutils
        - label: gdb
        - label: intrinsics
        - label: Java
        - label: KVM
        - label: ld
        - label: llvm
        - label: Linux kernel
        - label: QEMU
        - label: Spike
    validations:
      required: false
  - type: dropdown
    id: ratification-target
    attributes:
      label: Ratification Target
      description: Quarter and year of ratification.
      options:
        - 3Q2023
        - 4Q2023
        - 1Q2024
        - 2Q2024
        - 3Q2024
        - 4Q2024
    validations:
      required: true
  - type: textarea
    id: sow
    attributes:
      label: Statement of Work (SOW)
      description: The SOW information should be completed for each of the **bold** fields.
      value: |
        **Component names:**
        
        **Requirements:**
          (prose describing what has to be done and what the end result is)
        
        **Deliverables:**
          - Component_1 and changes expected.
          - Component_2 and changes expected.
          ...
        
        **Acceptance Criteria:**
          - Component_1 and measured result.
          - Component_2 and measured result.
          ...
        
        **Projected timeframe:** (best guess date)
        
        **SOW Signoffs:** (delete those not needed)
          - Task group liaison sign-off date:
          - Development partner sign-off date:
          - ACT SIG sign-off date (if ACT work):
          - Toolchains & Runtimes sign-off date (if gcc, LLVM, binutils, gdb work):
          - Privileged SW HC sign-off date (if QEMU, KVM, kernel, or OS work):
          - Application & Tools HC sign-off date (if POC or toolchain/library work):
        
    validations:
      required: false
  - type: checkboxes
    id: waiverflag
    attributes:
      label: Waiver
      description: If a waiver required for this work,  what type?
      options:
        - label: Freeze
        - label: Ratification
    validations:
      required: false
  - type: textarea
    id: pr-link
    attributes:
      label: Pull Request Details
      description: This field should contain links to the PR or mailing list patch submissions
      placeholder: |
        [PR #1](https://github.com/myproject/pulls/42)
    validations:
      required: false
