name: Development Partner Request
description: This is the template to request a RISC-V Development Partner work.
title: "[New DevPartner Request] - ADD A SHORT TITLE HERE"
labels: ["new", "planning", "developing", "in review", "done"]
body:
  - type: markdown
    attributes:
      value: |
        Please enter as much information as you can about the request.  Do not worry if you cannot complete everything.
  - type: input
    id: taskname
    attributes:
      label: Task Name
      description: Simple description of the task
      placeholder: ex. name, email@example.com
    validations:
      required: true
  - type: dropdown
    id: task-category
    attributes:
      label: Task Category
      description: What is the required skillset?
      options:
        - Arch Tests
        - Compilers/Toolchain
        - Libraries
        - Runtimes
        - SAIL model
        - Simulators
        - Specification
        - OS
        - Proof of Concept
        - Other
    validations:
      required: true
  - type: checkboxes
    id: task-subcategory
    attributes:
      label: Task Sub Category
      description: What is the required skillset?
      options:
        - gcc
        - binutils
        - gdb
        - intrinsics
        - Java
        - KVM
        - ld
        - llvm
        - Linux kernel
        - QEMU
        - Spike
    validations:
      required: false
  - type: dropdown
    id: ratification-target
    attributes:
      label: Repository Description
      description: Quarter and year of ratification.
      options:
        - 3Q2023
        - 4Q2023
        - 1Q2024
        - 2Q2024
        - 3Q2024
        - 4Q2024
    validations:
      required: true
  - type: textarea
    id: sow
    attributes:
      label: Link to SOW
      description: A link to the SOW document in Google Drive
    validations:
      required: false
