name: Development Partner Request
description: This is the template to request a RISC-V Development Partner work.
title: "[New DevPartner Request] - ADD A SHORT TITLE HERE"
labels: ["IITM", "PLCT", "RIOS", "Nambi", "10xE"]
body:
  - type: markdown
    attributes:
      value: |
        Please enter as much information as you can about the request.  Do not worry if you cannot complete everything.
  - type: dropdown
    id: tech-group
    attributes:
      label: Technical Group
      description: Which technical groups is requesting the work?
      options:
        - Applications & Tools HC
        - Architecture Test SIG
        - Code Size Reduction TG
        - Crypto TG
        - Debug TG
        - Golden Model SIG
        - ISA Infrastructure HC
        - Privileged Softwrae HC
        - Privileged Spec IC
        - Security HC
        - SOC Infrastructure HC
        - Technology HC
        - Unprivileged Spec IC
        - Other
    validations:
      required: true
  - type: input
    id: taskname
    attributes:
      label: Task Name
      description: Simple description of the task
      placeholder: ex. name, email@example.com
    validations:
      required: true
  - type: input
    id: tech-liason
    attributes:
      label: Technical Liason
      description: Name (email) for technical liason
      placeholder: ex. Jane Doe (email@example.com)
    validations:
      required: true
  - type: dropdown
    id: task-category
    attributes:
      label: Task Category
      description: What is the required skillset?
      options:
        - Arch Tests
        - Compilers/Toolchain
        - Libraries
        - Runtimes
        - SAIL model
        - Simulators
        - Specification
        - OS
        - Proof of Concept
        - Other
    validations:
      required: true
  - type: checkboxes
    id: task-subcategory
    attributes:
      label: Task Sub Category
      description: Select specific subcategories as needed.
      options:
        - label: gcc
        - label: binutils
        - label: gdb
        - label: intrinsics
        - label: Java
        - label: KVM
        - label: ld
        - label: llvm
        - label: Linux kernel
        - label: QEMU
        - label: Spike
    validations:
      required: false
  - type: dropdown
    id: ratification-target
    attributes:
      label: Ratification Target
      description: Quarter and year of ratification.
      options:
        - 3Q2023
        - 4Q2023
        - 1Q2024
        - 2Q2024
        - 3Q2024
        - 4Q2024
    validations:
      required: true
  - type: textarea
    id: sow
    attributes:
      label: Link to SOW
      description: A link to the SOW document in Google Drive
    validations:
      required: false
  - type: dropdown
    id: state
    attributes:
      label: State
      description: Work item state
      options:
        - new (Default)
        - sow
        - planning
        - developing
        - testing
        - in review
        - done
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Work item status
      options:
        - As-planned (Default)
        - At-risk
        - Blocked
        - Late
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: Size
      description: Estimated effort in single person months -- S (<3 mos), M (3-6 mos), L (6-12 mos), XL (1-2 yrs), XXL (>2 yrs)
      options:
        - Small
        - Medium
        - Large
        - Extra Large (XL)
        - Extra Extra Large (XXL)
    validations:
      required: false
  - type: checkboxes
    id: waiverflag
    attributes:
      label: Waiver
      description: If a waiver required for this work,  what type?
      options:
        - label: Freeze
        - label: Ratification
    validations:
      required: false
