name: Development Partner Request
description: This is the template to request a RISC-V Development Partner work.
title: "[New DevPartner Request] - ADD A SHORT TITLE HERE"
labels: ["new", "planning", "developing", "in review", "done"]
body:
  - type: markdown
    attributes:
      value: |
        Please enter as much information as you can about the request.  Do not worry if you cannot complete everything.
  - type: input
    id: taskname
    attributes:
      label: Task Name
      description: Simple description of the task
      placeholder: ex. name, email@example.com
    validations:
      required: true
